load(
    "@envoy//bazel:envoy_build_system.bzl",
    "envoy_cc_binary",
    "envoy_package",
)
load(
    # This file is generated by '//source:generator.py'.
    "//source:extensions.bzl",
    "ALL_EXTENSIONS",
)

licenses(["notice"])  # Apache 2

envoy_package()

envoy_cc_binary(
    name = "envoy-proxy-static",
    repository = "@envoy",
    stamped = True,
    deps = ALL_EXTENSIONS() + [
        # Envoy.
        "@envoy//source/exe:envoy_main_entry_lib",
    ],
)
