load("@envoy_api//bazel:api_build_system.bzl", "api_proto_package")

api_proto_package(
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//api/proxy/common/cache_api/v3:pkg",
        "//api/proxy/common/matcher/v3:pkg",
    ],
)
