load("@envoy_api//bazel:api_build_system.bzl", "api_proto_package")

licenses(["notice"])  # Apache 2

api_proto_package(
    deps = [
        "//api/proxy/common/cache_api/v3:pkg",
        "//api/proxy/common/matcher/v3:pkg",
    ],
)
